version: '3'

services:
  bot:
    container_name: CinnamonRP-bot
    build: .
    entrypoint:
      - node
      - bot/main.js
    depends_on:
      - db
    restart: always
  db:
    container_name: CinnamonRP-db
    image: mongo
    volumes:
      - "data:/data/db"
      - "./backup:/backup"
    restart: always

volumes:
  data:
    driver: local
